
# This workflow will do a clean installation of node dependencies.


name: Node.js Continous Integration of MY BLAND

on: push

jobs:
  build:

    runs-on: window-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    