
name: CI

on: push
jobs:
  build:
    runs-on: window-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "continous integretion finished seccessfull"
